added y/n prompts to install scripts

diff --git a/software/nvim_install b/software/nvim_install
--- a/software/nvim_install
+++ b/software/nvim_install
@@ -1,15 +1,21 @@
 #!/bin/bash
 set -e
 
-
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
-
-
+NVIM_CONFIG_DIR="$HOME/.config/nvim"
 "$SCRIPT_DIR"/../bin/pkg_install nvim --pacman neovim
 
 echo "Setting up nvim-kickstart.."
-mkdir -p ~/.config/nvim && cd ~/.config/nvim
-# NOTE: clear dir?
+if [[ -d "$NVIM_CONFIG_DIR" ]]; then
+    if $("$SCRIPT_DIR/../bin/prompt_y_n" "Do you want to clear $NVIM_CONFIG_DIR?"); then
+        rm -rf "$NVIM_CONFIG_DIR"
+    else
+        echo ":$0 error: Can't put configs over existing configs. Exiting.."
+        exit 1
+    fi
+fi
+
+mkdir -p "$NVIM_CONFIG_DIR" && cd "$NVIM_CONFIG_DIR"
 git clone https://github.com/nvim-lua/kickstart.nvim.git .
 echo "Patching nvim-kickstart.."
 # patch created with git diff >filename.patch
diff --git a/software/ranger_install b/software/ranger_install
--- a/software/ranger_install
+++ b/software/ranger_install
@@ -1,9 +1,19 @@
 #!/bin/bash
 set -e
 
-
 SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &> /dev/null && pwd)
+RANGER_CONFIG_DIR="$HOME/.config/ranger"
 
 "$SCRIPT_DIR"/../bin/pkg_install ranger
-mkdir -p ~/.config/ranger
-cp "$SCRIPT_DIR"/ranger/rc.conf ~/.config/ranger/
+
+if [[ -d "$RANGER_CONFIG_DIR" ]]; then
+    if $("$SCRIPT_DIR/../bin/prompt_y_n" "Do you want to clear $RANGER_CONFIG_DIR?"); then
+        rm -rf "$RANGER_CONFIG_DIR"
+    else
+        echo ":$0 error: Can't put configs over existing configs. Exiting.."
+        exit 1
+    fi
+fi
+
+mkdir -p "$RANGER_CONFIG_DIR"
+cp -r "$SCRIPT_DIR/ranger/"* "$RANGER_CONFIG_DIR"
